from .wavelet_transform import wavelet_l1, wavelet_l1_prox, wavelet_transform_2d, inv_wavelet_transform_2d
from .compressed_sensing import sparse_recover
from .total_variation import total_variation_denoising
